{% set version = "0.4.0" %}
{% set gh_org = "hackebrot" %}
{% set gh_repo = "poyo" %}

package:
  name: {{ gh_repo }}
  version: {{ version }}

source:
  fn: {{ gh_repo }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ gh_repo[0] }}/{{ gh_repo }}/{{ gh_repo }}-{{ version }}.tar.gz
  sha256: 8a95d95193eb0838117cc8847257bf17248ef6d157aaa55ea5c20509a87388b8

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - pytest
    - python
  commands:
    - py.test "{{ environ["SRC_DIR"] }}"

about:
  home: https://github.com/{{ gh_org }}/{{ gh_repo }}
  license: MIT
  summary: A lightweight YAML Parser for Python

extra:
  recipe-maintainers:
    - bollwyvl
